$script = <<SCRIPT
# Set Version
GOVERSION=1.8.3
GOHOME=/home/go
echo "Installing Go from https://storage.googleapis.com/golang/go$GOVERSION.linux-amd64.tar.gz"
curl -O https://storage.googleapis.com/golang/go$GOVERSION.linux-amd64.tar.gz
tar zxvf go$GOVERSION.linux-amd64.tar.gz
mv go /usr/local
useradd go -d $GOHOME
mkdir -p $GOHOME/go
echo "export GOPATH=$GOHOME/go" >> $GOHOME/.bash_profile
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 8080, host: 8081, host_ip: "127.0.0.1"
end
